# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: joshka
          template: classic
          base: header
          base_hireable: yes
          config_timezone: America/Los_Angeles
          plugin_languages: yes
          plugin_languages_ignored: php, html, css, scss, powershell, batchfile
          plugin_languages_limit: 7
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_notable_skipped: sonarr/sonarr
